# Shinken with just arbiter base image
# modules
#	
# VERSION	2.0.3

FROM     	dguenault/shinken:2.0.3	
MAINTAINER	David GUENAULT

# install supervisor configuration 
ADD     files/supervisor/shinken-scheduler.conf /etc/supervisord.d/

