# kunai base image
# VERSION    latest

FROM                debian:latest
MAINTAINER      David GUENAULT

# prerequisites
RUN      apt-get update && \
            apt-get -y install python-requests python-openssl python-setuptools python-pip python-leveldb git-core

